# Generated by Django 4.1 on 2023-12-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="data_added",
            new_name="date_added",
        ),
    ]
